### ISSUE TITLE
Auto zoom not working

### ISSUE THREAD

**Issue by jonathankapoor** [mapbox/mapboxgl-powerbi#204]
When a map visual is loaded or filtered (slicer, cross highlighting etc) the Mapbox visual doesn't automatically zoom.

**Comment by ryanbaumann** [comment]
Thanks for the issue @jonathankapoor - can you provide a screenshot of the issue and upload a power bi workbook file reproducing the issue?  What type of visualization layer are you using - circle, choropleth, etc?

**Comment by stephshadwell** [comment]
i was going to raise this today but thought it would be easier to keep as the same issue, as i have spotted this same issue on the new chloropleth map (circle maps seem to be zooming fine for me). I think it seems to default to the tileset layer as a whole, rather than filtering as per any filters within Power BI. The tileset in this example is the MSOA boundaries in England and Wales.

![image](https://user-images.githubusercontent.com/41364065/43384715-be4359f0-93d6-11e8-9d97-19ef2a5b658d.png)

**Comment by ryanbaumann** [comment]
Thanks, @stephshadwell, we're tracking autozoom to a subset of features in a tileset as part of https://github.com/mapbox/mapboxgl-powerbi/issues/133.  It's on our roadmap for the next release.

**Comment by stephshadwell** [comment]
Thats great to hear. Thanks @ryanbaumann
