### ISSUE TITLE
Mapbox Visual for Power BI doesn't display in Desktop on external monitor or some VMs without accelerated graphics

### ISSUE THREAD

**Issue by tonyberrynd** [mapbox/mapboxgl-powerbi#205]
I just installed the MapBox Visual from the marketplace and get blank view on PowerBI Desktop.  However, when I publish to PowerBI Service everything displays correctly.  

I have PowerBI Desktop running on a Macbook Pro 15" in a WIndows 10 image on VmWare Fusion 10.  

Any thoughts?

**Comment by ryanbaumann** [comment]
@tonyberrynd sounds like a Web GL support issue - does your Windows 10 VM on your Macbook have access to the GPU?  Try one of these pages -> https://get.webgl.org/ to confirm on your Windows machine using Chrome.

**Comment by tonyberrynd** [comment]
Thanks Ryan.  Looks like WebGL is enabled.  FYI, I also tried this in an Amazon Windows Server EC2 and get the same error.   

![image](https://user-images.githubusercontent.com/7888890/43367574-3992a184-931d-11e8-8893-bd5e615601c2.png)

I also tested on the June release of PowerBI Desktop and same issue.

**Comment by ryanbaumann** [comment]
Hmm, still seems WebGL related in PBI Desktop.  The EC2 Windows instance will have the same fundamental problem - access to the GPU.  Chrome itself has a software rendering fallback in swiftshader - I'll work with the Power BI team to see how we can debug this better.  Stay tuned.

**Comment by tonyberrynd** [comment]
Thanks.  Appreciate the help on this.

**Comment by ryanbaumann** [comment]
cc/ @samgehret

**Comment by Mike-Honey** [comment]
I'm seeing the same issue - I can see the WebGL spinning cube in Chrome, but all Mapbox tiles show blank in Power BI Desktop (31 July build). I'm running Windows Server 2016 Datacentre on Azure VM, via Remote Desktop Connection.  Same PBIX works fine on my laptop.

**Comment by ryanbaumann** [comment]
Thanks for the report @Mike-Honey.  Sounds like this is the same root cause - running PBI Desktop on a server without a dedicated GPU does not support WebGL in the current July 2018 build.  Continuing to work with the Microsoft team to troubleshoot.

**Comment by adamAdLad** [comment]
Hi Ryan

Any news on this one? Will the September version fix this? I have the same issue as Mike and Tony above. Both IE and Chrome show successful pages using the https://get.webgl.org pages.

The machine I connect to is a internal server is Intel(R) Xeon(R) CPU E5-2680 0 @2.70GHZ (12 processors) with 44 GB Ram running Windows Server 2016 64 bit OS. Display Adapater is  a VMware SVGA 3D Driver.

However in my case I use Terminal Services to connect to the Windows 2016 Server, do you think that is a problem? My own computer runs Webgl in IE and Chrome without problems too.

Regards

Adam

**Comment by samgehret** [comment]
@adamAdLad @Mike-Honey,  As  @ryanbaumann Chrome has a software rendering component embedded so I think Web GL will work in chrome even if there is no GPU present. The respsonse from the Power BI team was that Power BI desktop has no web rendering component built in. That's why it works when you publish, because you are viewing through a browser interface instead of the Desktop interface.

Working with the Power BI team to see if they will build in web rendering into desktop, but haven't heard back yet. Will keep everyone updated.

**Comment by Mike-Honey** [comment]
@samgehret - any update on this?

I'm now striking this in Power BI Desktop on a laptop (non-VM) which used to work fine.  I updating Mapbox CV to 1.3 didnt solve it (although it does now display a clear message). It's been a couple of months since I last worked on it so hard to isolate the cause - could be OS update, browser update, Power BI Desktop update ...
