### ISSUE TITLE
Hexagon grid and automatic binning (feature request)

### ISSUE THREAD

**Issue by ghost** [mapbox/mapboxgl-powerbi#225]
The ability to create a hexagon grid and then have it automatically count the data points would be a huge step forward in location data analytics within PowerBI. Anything that works towards this, even if its not fully automated at first, would be a great help.
So the result would be like the hexagonal bins created with full Mapbox and Turf, but syncronised to the rest of the dashboard.

I know I'm asking a lot but this feature would be a very powerful addition.

**Comment by ryanbaumann** [comment]
Great feature request @ChristopherWesson!  cc/ @samgehret

**Comment by DNC1971** [comment]
This would be even better if the hex bins worked on the H3: Uber's Hexagonal Hierarchical Spatial Index
which is an open source system. We are in the process of matching a lot of our data back to this great system.

**Comment by AltaherElhouderi** [comment]
Almost 4 years later, any updates on this?
I'm assuming this is now a lot easier to implement as a PowerBI visual since we have bindings for [Uber's H3 Hexagon Index](https://eng.uber.com/visualizing-city-cores-with-h3/) for JS/TS and C#/.NET (and many other languages)

https://h3geo.org/docs/community/bindings/

Would be a HUGE plus to also implement a `Play Axis`  field for the PBI visual (just like the `Scatter` visual).
Visualizing an animated temporal heatmap would be a total breeze compared to the current options of hassling with `folium` or `ipyleaflet`
