### ISSUE TITLE
Add Loading Notification

### ISSUE THREAD

**Issue by JayDoc386** [mapbox/mapboxgl-powerbi#245]
For end-users, it would be nice if they could see a notification that says "Map Loading" or something so that they know that nothing is wrong.  In Microsoft Power BI when you have a Mapbox Visual embedded, it can take some time to load and all the user will see in the interim is a white screen where the map should be.  Example of this is when using the ESRI Map add-in for Power BI it actually shows the ESRI logo and animated bars that signifying processing/loading.

**Comment by ryanbaumann** [comment]
This is a current limitation of the Microsoft Custom Visual framework AFAIK because the custom visual code is injected into the sandboxed iframe as a final step after all other assets are loaded on the page.  

I agree this would help the UX considerably - we'll work with the Microsoft team to see what improvements we can make.  Thanks, @JayDoc386!
