### ISSUE TITLE
Power BI Desktop shows Web GL error for Mapbox custom visuals

### ISSUE THREAD

**Issue by Mike-Honey** [mapbox/mapboxgl-powerbi#251]
I'm striking the Web GL error message in Power BI Desktop on a laptop which used to work fine up to late Sep. Updating Mapbox CV to 1.3 didnt solve it (although it does now display a clear message).

Web GL test page (https://get.webgl.org/) is working fine in Chrome, Edge, IE. Another test page (http://webglreport.com/) works fine in Chrome. Edge and IE works ok for "WebGL 1", but not "WebGL 2".  This is the same as on other machines running Windows 10 and I think expected?

I rolled Power BI Desktop back as far as the 11 Sep release (I know it was working after that) and I still get the Web GL error (on Mapbox CV 1.3, or blank on Mapbox CV 1.2). Same PBIX file works fine on another machine. 

On my laptop, starting a new empty PBIX and adding a Mapbox CV or starting from an existing PBIX and adding a Mapbox CV both result in the Web GL error.

Can anyone help me resolve this - I'm stumped on what to try next.  It's clearly not the file, not Power BI Desktop, not my browser, so it must be something else on that laptop, that changed since late September 2018?

**Comment by ryanbaumann** [comment]
Thanks, @Mike-Honey - this is a known issue for PBI desktop (external monitor support causes a webGL error).  I'm going to close this issue here since the broader issue of WebGL support in PBI Desktop is captured https://github.com/mapbox/mapboxgl-powerbi/issues/71, and we're continuing to work with the Power BI team on a solution that works with Mapbox Visual and PBI Desktop across more hardware.
