### ISSUE TITLE
Point disappears on circle map, when only 1 result return

### ISSUE THREAD

**Issue by stephshadwell** [mapbox/mapboxgl-powerbi#259]
On the circle map type, if only 1 point returned, the map does not display the circle, see examples below (currently using v1.3 from app store)

**Multiple reports returned**
![image](https://user-images.githubusercontent.com/41364065/48140010-c950e700-e29f-11e8-85fa-7d0bac0cce64.png)

**Single point returned**
![image](https://user-images.githubusercontent.com/41364065/48140024-d40b7c00-e29f-11e8-9bc3-3af89ca4da7b.png)

**Comment by intothenight** [comment]
It would be great if this could be fixed

**Comment by ryanbaumann** [comment]
This is a bug to fix, thank you for highlighting @stephshadwell.  Do you have a sample PBIX workbook you could attach to the ticket for us to easily replicate with?

cc/ @samgehret

**Comment by stephshadwell** [comment]
@ryanbaumann  see attached example file with 3 examples
Example 1 - circles do not disappear (size option not used)
Example 2 - circles disappear (longitude, latitude, size & colour options used)
Example 3 - circles disappear (longitude, latitude & size used)

Hope that helps

[Example file - single point.zip](https://github.com/mapbox/mapboxgl-powerbi/files/2638978/Example.file.-.single.point.zip)

**Comment by indiciagerry** [comment]
Same as : https://github.com/mapbox/mapboxgl-powerbi/issues/180

**Comment by indiciagerry** [comment]
This one is a major show stopper (since the start in june 2018).
We can show thousands of pins but not one...

Please put this bug in the priority 1 bin!

**Comment by mattdlewis** [comment]
Yup this is really confusing - users think they've made a mistake

**Comment by ryanbaumann** [comment]
We'll get this on the docket to fix in the next release.  Thanks for flagging.  cc/ @samgehret

**Comment by indiciagerry** [comment]
Please put this in 1.5! @ryanbaumann

**Comment by ryanbaumann** [comment]
Will do, agree this is a must-fix bug @indiciagerry 🙏

**Comment by warrendean81** [comment]
Glad I found this post. I have been playing around with settings for ages trying to work out what was wrong!!

**Comment by mattdlewis** [comment]
Is this still an outstanding bug? — everything's still disappearing when I filter down to 1 circle.

**Comment by ryanbaumann** [comment]
Yes, this issue is still open.  We're scoping a bug fix for our next release.  cc/ @samgehret

**Comment by TonyGaul** [comment]
Hello, in my experience the issue is not limited to a single data point / circle.  The circles disappear when the "size" value is the same for every row of data.  For example if the size value is 1 for 100 rows of data that have different lat/lon coordinates, the circles do not show.
[Mapbox size issue.zip](https://github.com/mapbox/mapboxgl-powerbi/files/3705474/Mapbox.size.issue.zip)

**Comment by ryanbaumann** [comment]
Thanks for the extra test case @TonyGaul.  We're actively looking at fixing this bug now in our current project 1.5

**Comment by TonyGaul** [comment]
@ryanbaumann Hey Ryan, do yo have an eta for 1.5 release or at least a 1.5 beta with this issue fixed?

**Comment by ryanbaumann** [comment]
@TonyGaul I'm working on a v1.5.0 release as a security fix and pricing update.  We will quickly begin v1.6.0 and add this bug fix to the must-haves.

**Comment by TonyGaul** [comment]
@ryanbaumann Thanks for the update!

**Comment by luisroffers** [comment]
February 2020: still have issues with mapbox in power BI. When I select an item in a matrix or list (or any slicer), all pins disappear and map zooms in to where location actually is, but all markers are gone. Any update on this?

**Comment by ValentinMaz** [comment]
April 2020: still the case with mapbox in Power BI - the circle does no show if there is a filtered selection on only one Item. Whenever there is more than one circle they all display fine
Any news?

**Comment by intothenight** [comment]
Eta 2022. Worse part is I was contacted by Mapbox asking me how using the Power BI plug-in was going. I response I used it for a week when it first launched, it didn’t work, and I’ve been waiting since for this bug to be fixed. No response so far. The world moves on.

**Comment by Drew-github** [comment]
July 2020: Is there no fix yet. I have the same problem except I can display a single point if I don't use a field for Color and Size. As soon as I add a field to Size, my circle disappears. 

I spent hours mucking around with different settings and reloading data. You'd think this would be easy enough to sort out.

**Comment by seanghgh** [comment]
@ryanbaumann Hi Ryan, any plan for fixing this bug? This has been open since 3 years ago and a very important one. Can you please provide an update? Much appreciated.

**Comment by macmoledo** [comment]
Hi there! Is there any plan to fix this bug? I'm not a pro and not sure if it is something difficult to fix, but with all due respect, this thread goes back to November 2018 and a few viewers have already enquired. An update will be much appreciated. Regards.

**Comment by soliverc** [comment]
I'm currently trying to deal with this bug. Will it be fixed?

**Comment by LetsGitIt-718** [comment]
If anyone wants an alternative, dTyp has a visualization called "Data Map", it has the capability of using Mapbox (Visual Settings > Base Map > Mapbox Light) with your current API key (and a limited selection of map styles). This issue is not present in that visualization. The bubbles can be adjusted but they don't auto-scale with the data, you will have to create a custom value to assign the circle sizes, I didn't go above 25 for my visual size.
![image](https://user-images.githubusercontent.com/76823742/154159691-df172d29-f53b-4a5c-bcf0-f46e982d132f.png)

**Comment by martinedoesgis** [comment]
+1

**Comment by mate-turi** [comment]
This bug has already been fixed in the new project.
Github: [https://github.com/starschema/mapboxgl-powerbi/](https://github.com/starschema/mapboxgl-powerbi/)
AppSource: [https://appsource.microsoft.com/en-us/product/power-bi-visuals/olgaltatokorlatoltfelelossegutarsasag1643647545884.mapbox_pbi_custom_visual?tab=Overview](https://appsource.microsoft.com/en-us/product/power-bi-visuals/olgaltatokorlatoltfelelossegutarsasag1643647545884.mapbox_pbi_custom_visual?tab=Overview)

**Comment by magicaly2** [comment]
The disappearing circle issue is fixed
but came out new error when selecting 1 result

<img width="489" alt="image" src="https://user-images.githubusercontent.com/58059218/220497909-1296a168-ebc2-4061-a4a2-e94489ec025c.png">
The error comes out when i have measure in [Size]
<img width="101" alt="image" src="https://user-images.githubusercontent.com/58059218/220498023-fe0bf531-f427-48aa-9471-db619f918f5f.png">


Im using latest MapBox Custom Visual v1.6.01

<img width="554" alt="image" src="https://user-images.githubusercontent.com/58059218/220497678-4a330d8a-9ffa-4ecf-908b-de4a31f997e8.png">
