### ISSUE TITLE
User configurable domain values for layer min, med & max values

### ISSUE THREAD

**Issue by James-Henry31** [mapbox/mapboxgl-powerbi#266]
Hi,

Following a conversations with Madison Draper (@mzdraper ) would it be possible to create input values when setting the min, med and max colors when using the choropleth mapping option in Power BI. The issue I am facing at the moment is that my data set is quite large and I am mapping this into LSOA areas. As the value colors are set automatically and are based off the total data set it means that everything is the min color due the large number of areas I have to map across.

**Comment by mjoseph155** [comment]
Hi,

Also following a conversation with Madison Draper, I'll add my support to this change. In my case, I have 2 maps side by side, one choropleth map and one with circles on specific long/lat coordinates. In my use case I'd like to be able to click into  a country on the choropleth map, then show the circles with set colours depending on their value (e.g. 0-85, 85-99, 100 as 3 distinct colours) rather than using a min/med/max scale between 3 colours. 

I can do this using the Power BI Bing Maps visualisation by setting up rules under the Advanced controls setting in the Data colors option (image below), but performance is shocking with a decent amount of data, and I'd much rather use Mapbox if I can.

![bingcolourrules](https://user-images.githubusercontent.com/45824967/49881259-d3797e80-fe25-11e8-90d9-65b317afed69.PNG)

**Comment by samgehret** [comment]
@James-Henry31 we just released a new feature to the marketplace which should address this issue: https://github.com/mapbox/mapboxgl-powerbi/issues/212

Can you give it a try and see if it helps you?

**Comment by otravers** [comment]
I don't know if this should be tracked in this issue, or be the topic of a new one, but the "format by rules" conditional formatting option shown above by @mjoseph155 is more powerful than the static thresholds from #212 (which, mind you, are great to have!).

This originally was a feature in tables:
https://docs.microsoft.com/en-us/power-bi/desktop-conditional-table-formatting

Recently it's been extended to other default chart types, as shown below in the _Advanced Controls_ under _Data colors_ for a Stacked bar chart:
![image](https://user-images.githubusercontent.com/3731532/54918637-92414200-4edd-11e9-8f5d-94464e2f8602.png)

When you select "Format by rules", you can base the rule on a column, calculated column, or even better, on a measure. This means you can use expression-based formatting, i.e. drive formatting with a dynamic DAX calculation rather than a static, hard-coded value. This lets you drive your formatting with KPI-like business logic, as well as input more than three thresholds. Very powerful and flexible!

Microsoft is even considering letting us put a DAX expression directly there, similarly to how SSRS works:
https://docs.microsoft.com/en-us/business-applications-release-notes/april19/business-intelligence/power-bi-desktop/expression-based-formatting
