### ISSUE TITLE
Docs Example Request - Adding a Raster Layer in Power BI

### ISSUE THREAD

**Issue by SWRB** [mapbox/mapboxgl-powerbi#309]
Hi, following a customer question, it would be great to have a docs example for how to add a raster layer (example openweather.gov.api) to a Mapbox base map in Power BI. 

For both WMS and ZXY tile format. 

Thanks! 

cc. @ryanbaumann

**Comment by ryanbaumann** [comment]
* XYZ tile format 
    * Acceptable URL format: `https://{domain}/{endpoint}/{z}/{x}/{y}{@2x}.png`
    * Example URL to add as raster source to PowerBI:  https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}@2x.png
    * Tile Size: 256, unless otherwise specified by your tile source
* WMS tile format
    * Acceptable URL format: `http{s}://{domain}/{endpoint}?bbox={bbox-epsg-3857}&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers={my-wms-layers}`
    * Notes - always include `bbox={bbox-epsg-3857}` URL parameter in WMS request
    * Example URL to add as raster tile source to Power BI - https://img.nj.gov/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015

**Comment by otravers** [comment]
I'm concerned about the discoverability of WMS URLs. Publishers typically publish a GetCapabilities URL, for instance:
https://mrdata.usgs.gov/services/mrds?request=getcapabilities&service=WMS&version=1.3.0&

If you browse Data.gov, Spatineo etc. this is what you will get. If I feed GetCapabilities URLs like the one above into, say, QGIS, it figures out how to get the tiles and legend. Do we have to guess the tile endpoint URL? Because I've tried to do that manually and haven't always been successful, and at best it's time consuming.

I might just be confused though, I'm not a WMS expert by any stretch.
