### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by suri1996** [mapbox/mapboxgl-powerbi#310]
We put a MapBox Map into our visual.

As shown in the screenshot below, we put the field 'Utilization %' into the tooltip and it displays the value correctly.

![image](https://user-images.githubusercontent.com/13168204/58680084-d4cd4200-8398-11e9-8bde-c489fe6889be.png)

When the Year 2019 is selected, the tooltip shows the correct info

![image](https://user-images.githubusercontent.com/13168204/58680179-368dac00-8399-11e9-83ee-9a48002a7aa4.png)

We'd also like to add a field 'POL Country' into the tooltip so that the customers can see the country name as well the Utilization % when they hover over a country.

To do that, I drag and drop the “PolCountryName” into the tooltip section.
As you can see from the screen shot, the right click options only has first / last / count distinct / count. There is no option for “Don’t summarize”.
By default, "First" is chosen.

![image](https://user-images.githubusercontent.com/13168204/58680334-f7ac2600-8399-11e9-8f74-cecbb7d083e7.png)

If I activate the tooltip for “First PolCountryName”, the name of “Australia” will not appear in the tooltip because it forces me to choose the first name appeared as one of the aggregate function.

![image](https://user-images.githubusercontent.com/13168204/58680358-10b4d700-839a-11e9-8834-96327d292685.png)

If I filter “First PolCountryName = is not blank”, you can see that Australia will be excluded from the map but this is not the result I want.

![image](https://user-images.githubusercontent.com/13168204/58680366-14e0f480-839a-11e9-93a1-24117252a41a.png)

If I check the data from a table visual, you can see that only Germany / China / India appeared in the “First PolCountryName” column which is auto generated on inserting the Pol Country field into the tooltip, which is why all other locations (including Australia) disappeared in the map.

![image](https://user-images.githubusercontent.com/13168204/58680377-1c080280-839a-11e9-8381-5dce927d91c3.png)

**Comment by ryanbaumann** [comment]
Thanks for a detailed ticket on this bug @suri1996 .  This looks like a grouping / aggregation bug where a specific dimension from your dataset is excluded when aggregated.  

The reason why we enforce aggregation for the `color`, `size`, and `tooltip` fields is because the map visual is anchored by location dimensions - `location` or `longitude/latitude` - with summarized attributes, one per dimensions - `color`, `size`, `tooltip`.  

The solution here is to understand what you want to display in your tooltip - if there was a `don't summarize` option, what would you expect the tooltip to say?  And how would the corresponding raw data table look?

Hunch to investigate here - `null` measure options in `color`, `tooltip`, etc. cause those data rows to be excluded from the map visual (as your raw data table shows, AU is missing).  

Is it possible to attach this PBI workbook as an example to investigate to this ticket?

cc/ @samgehret

**Comment by suri1996** [comment]
Many thanks for your feedback.

Please find attached the sample PBI file for your reference with the tooltip issues.
The problematic map and tooltip issues can be found in the "POLCountryMap" tab.

Table visuals of the POLCountry column can be found in the "Snap shot of dataset" tab.

- Left table has the "Id" and "PolCountryName" column from the database. Each record from our database is associated with a unique "Id" but you can see that many "Id" do not have a proper "PolCountryName" and that's why it classified as "null".
- Middle table is grouped by "PolCountryName" and you can see that there are 2634 records that do not have a "PolCountryName" associated to it.
- Right table is just to simulate if I aggregate the data as "First PolCountryName".

Please see if there are any possibilities to fix the bug in MapBox or advise us the best possible alternatives to sort this matter out.
Thank you so much!! 

[KPIs - MapBox issue.pbix.zip](https://github.com/mapbox/mapboxgl-powerbi/files/3279520/KPIs.-.MapBox.issue.pbix.zip)
