### ISSUE TITLE
Repetition in attribution text

### ISSUE THREAD

**Issue by martinedoesgis** [mapbox/mapboxgl-powerbi#399]
In the map attribution the text is repeated, making it quite long. 

![image](https://user-images.githubusercontent.com/34961989/158995896-cd0ea505-03ab-432c-bddf-b9a1d4f354ac.png)

Could be only the second part : @Mapbox @OpenStreetMap **Improve this map**

**Comment by Vamshi30326** [comment]
11)Link your Mapbox access token in Power BI
2)To use the Mapbox Visual in Microsoft Power BI, you need to link your Mapbox access token in Power BI:
3)To get started with the Mapbox Visual in Microsoft Power BI, you need a Mapbox account and a Mapbox access token. You 
  can find your Mapbox access tokens on your Account page.
4)In Power BI, under the Mapbox Custom Visual Format panel, open the Viz Settings dropdown.
5)Paste your Mapbox access token in the Access Token field.
6)Use a custom Mapbox style in Power BI
7)The Mapbox Visual for Power BI gives you access to several default Mapbox styles. You can also use a custom Mapbox that 
   you have created in Mapbox Studio:
8)In Mapbox Studio, find the style that you want to use.
9)Click the Menu button.
10)Click the icon next to the Style URL to copy it to your clipboard. You will need this URL to link to your custom map style in Power BI.
11)Go to Power BI. Under the Mapbox Custom Visual Format panel, open the Viz Settings dropdown.
12)In the Map Style field, select the Custom option.
13)In the Style URL field, paste the style URL that you copied earlier.
14)Format your location data to use in Power BI choropleth visualizations
15)The Mapbox Visual for Power BI provides default support for creating choropleth visualizations at different administrative 
     levels.
[Style dimensional values with the Data Colors feature]
If you format your data so that the values in categorical (dimension) field are text, you can style these dimensional values using the Data Colors feature. The Power BI interface hides this feature until you have met the following data and format conditions.
To access the Data Colors feature:
Format your data and import it into Power BI. The values in the dimensional field you want to use must be formatted as text.
Begin creating your Power BI report as usual, and add the Mapbox Visual.
Drag your dimensional field from the Fields panel into the Color shelf.
The Data Colors dropdown menu will appear in the Format panel. Select your desired colors for each text value
You can also use the Data Colors field to style your choropleth visualizations in Power BI:
You can also use the Data Colors field to style your choropleth visualizations in Power BI:
(https://drive.google.com/file/d/1ZTKFbmRA84HTQ96h6uVrSvkD1P8O7JSU/view?usp=sharing)
Format your data and import it into Power BI. The values in the dimensional field you want to use must be formatted as text.
Begin creating your Power BI report as usual, and add the Mapbox Visual.
Make sure that the data you drop into the Location field in the Mapbox Visual exactly matches the data in a default Mapbox Visual dataset (see the [Format your location data to use in Power BI section](https://docs.mapbox.com/help/troubleshooting/integrate-mapbox-visual-with-power-bi/#format-your-location-data-to-use-in-power-bi-choropleth-visualizations)).
Drag your dimensional field from the Fields panel into the Color shelf.
Go back to the Format tab. Switch the Circle option off and turn the Choropleth option on.
The Data Colors dropdown menu will appear. Select your desired colors for each text value.
Format your data and import it into Power BI. The values in the dimensional field you want to use must be formatted as text.
Begin creating your Power BI report as usual, and add the Mapbox Visual.
Make sure that the data you drop into the Location field in the Mapbox Visual exactly matches the data in a default Mapbox Visual datasetDrag your dimensional field from the Fields panel into the Color shelf.
Go back to the Format tab. Switch the Circle option off and turn the Choropleth option on.
The Data Colors dropdown menu will appear. Select your desired colors for each text value.
You can also use the Data Colors field to style your choropleth visualizations in Power BI:

Format your data and import it into Power BI. The values in the dimensional field you want to use must be formatted as text.
Begin creating your Power BI report as usual, and add the Mapbox Visual.
Make sure that the data you drop into the Location field in the Mapbox Visual exactly matches the data in a default Mapbox Visual dataset 
Drag your dimensional field from the Fields panel into the Color shelf.
Go back to the Format tab. Switch the Circle option off and turn the Choropleth option on.
The Data Colors dropdown menu will appear. Select your desired colors for each text value.
https://drive.google.com/file/d/1SY9ofDjQQjHa6zBsWllyiXW_XPPAomH2/view?usp=sharing
[Resolve blank map issues in Power BI](https://docs.mapbox.com/help/troubleshooting/integrate-mapbox-visual-with-power-bi/#resolve-blank-map-issues-in-power-bi)
If a map that you created with the Mapbox Visual for Power BI does not display, this can likely be traced to one of the following issues:

No GPU. If your map does not display and you are using Power BI Desktop, this likely means that the machine does not have a graphics processing unit (GPU). The Mapbox custom visual for Power BI uses Mapbox GL, which requires a GPU to do client-side rendering,
This is a common case when Power BI Desktop is running on a virtual machine. Mapbox GL needs access to the GPU, and virtual machines don't generally have access to the GPU without hardware acceleration enabled. Check to see if you have hardware acceleration enabled on the virtual machine — if not, you will need to enable it.
Cache needs to be cleared. If your map does not display in Power BI Web or Power BI Desktop, either the browser cache or the Power BI Desktop cache may need to be cleared. This can happen due to occasional problems with the Power BI marketplace. To clear the Power BI Desktop cache, delete the contents of the following folders:
C:\Users\%username%\AppData\Local\Microsoft\Power BI Desktop
C:\Users\%username%\Microsoft\Power BI Desktop Store App
No access to Mapbox API endpoints. If your map does not display in Power BI Web or Power BI Desktop, the machine running Power BI Web or Power BI Desktop may not have access to the Mapbox API endpoints. While no customer data is ever sent to Mapbox, the Mapbox API endpoints must be accessible for rendering Mapbox tiles and styles:
https://*.tiles.mapbox.com
https://api.mapbox.com
